### ISSUE TITLE
Conflicts in environment.yml

### ISSUE THREAD

**Issue by JankowskiChristopher** [adityab/CrossQ#2]
Hello,
Could you please check whether installation of your requirements work correctly?
When I was trying to run the code, I got errors with pip resolver stating problems with `torch` version - most probably it was conflicting with JAX and CUDA. I was able to run your code with the requirements below, but I had to downgrade `torch` and I am worried that I might not reproduce your results due to this. 

My requirements.txt:

```
absl-py==2.0.0
appdirs==1.4.4
brax==0.0.16
cachetools==5.3.1
certifi==2023.7.22
charset-normalizer==3.3.1
chex==0.1.84
click==8.1.7
cloudpickle==3.0.0
contextlib2==21.6.0
contourpy==1.1.1
cycler==0.12.1
dataclasses==0.6
decorator==5.1.1
distrax==0.1.4
dm-env==1.6
dm-tree==0.1.8
docker-pycreds==0.4.0
etils==1.5.1
Farama-Notifications==0.0.4
filelock==3.12.4
flax==0.7.4
fonttools==4.43.1
fsspec==2023.10.0
gast==0.5.4
gitdb==4.0.11
GitPython==3.1.40
glfw==2.6.2
google-auth==2.23.3
google-auth-oauthlib==1.0.0
grpcio==1.59.0
gym==0.26.2
gym-notices==0.0.8
gymnasium==0.29.1
idna==3.4
imageio==2.34.0
importlib-resources==6.1.0
jax==0.4.19
jaxlib==0.4.19+cuda12.cudnn89
Jinja2==3.1.2
kiwisolver==1.4.5
labmaze==1.0.6
lxml==5.1.0
Markdown==3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.0
mdurl==0.1.2
ml-collections==0.1.1
ml-dtypes==0.3.1
mpmath==1.3.0
msgpack==1.0.7
mujoco==2.3.7
nest-asyncio==1.5.8
networkx==3.2
numpy==1.26.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.3.2.9
nvidia-cuda-cupti-cu12==12.3.52
nvidia-cuda-nvcc-cu12==12.3.52
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.3.52
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.11.19
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.5.3.52
nvidia-cusparse-cu12==12.1.3.153
nvidia-nccl-cu12==2.18.3
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
opt-einsum==3.3.0
optax==0.1.7
orbax-checkpoint==0.4.1
packaging==23.2
pandas==2.1.1
pathtools==0.1.2
Pillow==10.1.0
protobuf==4.24.4
psutil==5.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
Pygments==2.16.1
PyOpenGL==3.1.7
pyparsing==3.1.1
python-dateutil==2.8.2
pytinyrenderer==0.0.14
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.2
rlax==0.1.6
rsa==4.9
scipy==1.11.3
sentry-sdk==1.32.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
stable-baselines3==2.1.0
sympy==1.12
tensorboard==2.14.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
tensorflow-probability==0.21.0
tensorstore==0.1.46
tfp-nightly==0.20.0.dev20230524
toolz==0.12.0
torch==1.13.1
tqdm==4.66.1
trimesh==4.1.4
triton==2.1.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==2.0.7
wandb==0.15.10
Werkzeug==3.0.0
zipp==3.17.0
```

**Comment by JankowskiChristopher** [comment]
@adityab thanks for updating the README. With the changes in README this issue might no longer be relevant - I still got some errors with torch version, but I guess that maybe they can be ignored, as I was able to run the code with the instructions from README (The code run but the issue #3 unfortunately still persists). If we run the code with current instructions maybe even the `environment.yml` is not needed anymore?

Side note: `install.sh` has old README instruction with the wrong JAX version. It could be beneficial to update it as well or maybe even delete this script as the instruction is provided in the README.

**Comment by adityab** [comment]
You're right, those files are not useful, I just deleted `environment.yml` and `install.sh`. The README instructions are all you need now. :sweat_smile: 

> still got some errors with torch version, but I guess that maybe they can be ignored

Yes, you're probably seeing these when installing JAX, and you can ignore them here.
![Screenshot from 2024-04-08 14-58-23](https://github.com/adityab/CrossQ/assets/591038/1d0f8857-4a52-4fb6-8f18-8d712fed2c8e)

Thanks for pointing this out!
