### ISSUE TITLE
Improvement in default args

### ISSUE THREAD

**Issue by JankowskiChristopher** [adityab/CrossQ#4]
Hello,
I have a tiny suggestion to improve the code.  In `train.py`, the current default algo is SAC, which is a little bit counter intuitive for the CrossQ repository. My suggestion is to change it to `crossq` in case user forgets to change it when running.

Suggested change:
```
parser.add_argument("--algo", type=str, required=False, default='crossq', choices=['crossq', 'sac', 'redq', 'droq', 'td3'], help="agent to run")
```
side note: currently in `help` there is a typo - "critic activation function" instead of help related to choosing the agent.

**Comment by adityab** [comment]
Just pushed the following

- improved the argument `help` captions in `train.py`.
- set `required=True` on `algo` so people know what they're running. :wink: 

Thanks for the pointers!
